spring.application.name=KISlab6

spring.datasource.url=jdbc:postgresql://localhost:5432/lab6
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:mybatis/mappers/*.xml
mybatis.type-aliases-package=ru.miit.kislab6.model
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true